### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by mzhadigerov** [didi/ChineseNLP#38]
How to access the source code for Relation Extraction. I could not find it in this repository.

**Comment by Huang17** [comment]
Can you be more specific? Which source code you are referring to?

**Comment by mzhadigerov** [comment]
@Huang17 Hi! I'm interested in Familial Relation Extraction solution : https://github.com/didi/ChineseNLP/blob/master/docs/relation_extraction.md

Is there any source code available for this? I mean the implementation.

**Comment by Huang17** [comment]
@mzhadigerov Hi, as you can see in the [Relation Extraction page](https://github.com/didi/ChineseNLP/blob/master/docs/relation_extraction.md), we introduced two datasets ACE 2005 Relation Extraction and Chinese-Literature-NER-RE-Dataset and both datasets contains family type of relation. And we have listed links about datasets.

If you are interested in source code of any specific paper listed in the Relation Extraction page, I'd recommend you contact the author directly. 

ChineseNLP is a project to collect shared tasks, datasets and state-of-the-art results for Chinese Natural Language Processing (NLP) and we don't provide additional implementation of papers.

**Comment by Huang17** [comment]
I’m closing this issue because it has been inactive for a few months.
