### ISSUE TITLE
咨询co-reference_resolution.md的问题

### ISSUE THREAD

**Issue by CuiYan72** [didi/ChineseNLP#9]
请问您在共指消解上实现的输入输出是这篇《Deep Reinforcement Learning for Mention-Ranking Coreference Models》文章吗？方便提供源码吗？

**Comment by Huang17** [comment]
你好, 我们只是汇总整理了论文《Deep Reinforcement Learning for Mention-Ranking Coreference Models》中的结果,并没额外写测试代码. 另外论文有在Github开源 相关[代码](https://github.com/clarkkev/deep-coref) ,供参考.

**Comment by Huang17** [comment]
I’m closing this issue because it has been inactive for a few months.
